services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.product
    restart: always
    env_file:
      - ./postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres.env
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    depends_on:
      - db

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile.product
    ports:
      - 80:80
    depends_on:
      - db
      - api

volumes:
  postgres_data: