services:
  db:
    image: postgres:16.1-bookworm
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # csvインポート作業時にコメントアウトを外す
      # - ./csv:/csv

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./api.py:/app/api.py
    depends_on:
      - db
    
volumes:
  postgres_data: