services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres.env

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - 5000:5000
    command: python manage.py
    volumes:
      - ./api:/app
    depends_on:
      - db
    