services:
  db:
    image: postgres:16.1-bookworm
    restart: always
    env_file:
      - ./postgres.env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # csvインポート作業時にコメントアウトを外す
      # - ./db/csv:/csv

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres.env
    ports:
      - 5000:5000
    command: python manage.py
    volumes:
      - ./api:/app
    depends_on:
      - db
    
volumes:
  postgres_data: